apiVersion: v2
dependencies:
- alias: internal-ingress-nginx
  condition: internal-ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.11.5
- alias: external-ingress-nginx
  condition: external-ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.11.5
- condition: tempo.enabled
  name: tempo
  repository: https://grafana.github.io/helm-charts
  version: 1.7.1
description: Helm chart for the ingress-nginx-controller
name: nginx-ingess
type: application
version: 1.0.0
